### ISSUE TITLE
Allow additional markup outside docstrings

### ISSUE THREAD

**Issue by jneug** [Mc-Zen/tidy#11]
It would be nice to be able to structure the documentation by allowing additional markup in a module file, that is not attached to a function. For example:
```typst
/// == Utility functions
/// The following functions are utilities.

/// A foo function.
#let foo(a, b) = [#a-#b]

/// == Math functions
/// Some math markup

#let inv(x) = $1/x$
```

After rendering and parsing, the headings and descriptive text would render between function documentation.

Open question:
- How to handle this additional markup with `sort-function`?

**Comment by Mc-Zen** [comment]
Hi @jneug ,

I would actually suggest putting utility and math functions into two different modules, `utilities.typ` and `math.typ`. You can include both from within your main lib file, 
```typ
// lib.typ
#import "utilities.typ": *
#import "math.typ": *
```
(so to the outside it makes no difference) and show both modules individually. You then have more control on how everything is styled. In the future, I also plan on adding file descriptions.

**Comment by johannes-wolf** [comment]
The possibility to add doc-strings to variables (e.g. dictionaries) would be very nice, too!

**Comment by Mc-Zen** [comment]
Hi @johannes-wolf yes, this is definitely necessary! You can already put docstrings in front of variables and they will be recognized. Unfortunately, they are recognized as functions 😄. The initial idea was that this way we can document alias functions 

`#let my-line = line.with(stroke: 2pt)`

but I think this behaviour should be changed. The resulting dictionary from the `parse-module()` step will then contain another list at `"definitions"` in addition to `"functions"`.

**Comment by Mc-Zen** [comment]
Hi @jneug,
as stated above, I would suggest putting two different "parts" of the code into two modules for your purpose. Otherwise, the order of the function declarations also matters for the documentation which is not ideal, I feel. 

However, we can add support for file/module descriptions that can be put at the top of a file. If you have suggestions regarding this, feel free to post them here :)

**Comment by Mc-Zen** [comment]
Closing with merge of #26
