### ISSUE TITLE
Different type labels from official document (`str`→`string`, `int` → `integer`, etc.)

### ISSUE THREAD

**Issue by mkpoli** [Mc-Zen/tidy#16]
It seems that the labels of `str` and `int` type is different between `tidy` and Typst's official documentation, where

the `string` type is `str` 
![image](https://github.com/Mc-Zen/tidy/assets/3502597/1b8c3256-17f0-48a2-8a80-da246fc67947)
https://typst.app/docs/reference/foundations/str/

the `integer` type is `int`
![image](https://github.com/Mc-Zen/tidy/assets/3502597/77c61b58-d327-4731-aefd-19ee06b0abd7)
https://typst.app/docs/reference/foundations/int/

It seems that in old version of Typst, `type(1)` yields `"integer"`, so is this a legacy or is it intended?

**Comment by Mc-Zen** [comment]
This is indeed legacy and also applies to `relative` (which was originally `relative length`).

**Comment by Mc-Zen** [comment]
The old versions will also be supported in favour of backwards-compatibility
