### ISSUE TITLE
Document font dependency (Cascadia Mono)

### ISSUE THREAD

**Issue by sahasatvik** [Mc-Zen/tidy#18]
It would be nice if the fact that the default styles require Cascadia Mono is documented somewhere. Although this font is available in the webapp, it's probably not installed by default on non Microsoft systems.

**Comment by Mc-Zen** [comment]
Hi, I wasn't aware of this. The default style uses Cascadia Mono as this is the font used by the online documentation of Typst. What happens exactly when the font is not available? Does it fallback to some other monospaced font?

**Comment by sahasatvik** [comment]
On my system, it seemed to fallback to a _non_ monospaced font (after all, the `text(...)` command can't really tell what kind of font is missing).

**Comment by Mc-Zen** [comment]
Good point, I will add a (or more than one) suitable fallback ... or maybe I could even replace the `text` with a `raw`. The problem is only that the user might use show rules on `raw`, so maybe it's better to wait for `revoke`.

**Comment by sahasatvik** [comment]
Sounds good. I only brought this up since I initially thought that the package was broken because of the weird rendering, hence I went digging in the source files. Installing the right font isn't actually much of a hassle once you know what it is (honestly, this is the first time I've heard of Cascadia). Perhaps a note in the README along the lines of "looks best with Cascadia Mono ..." will suffice for now.
