### ISSUE TITLE
raw elements in examples are explicitly set to `block: true`

### ISSUE THREAD

**Issue by SillyFreak** [Mc-Zen/tidy#21]
Reproducing example:

`````
#import "@preview/tidy:0.3.0"

#let module = ````
/// #example(```
/// [a #raw("foo") b]
/// ```)
let x = none
````.text

#let module = tidy.parse-module(
  module,
)
#tidy.show-module(
  module,
  sort-functions: none,
  style: tidy.styles.minimal,
)
`````

This uses `#raw("foo")` in an example. By default, this would not result in inline raw content, but due to [this line](https://github.com/Mc-Zen/tidy/blob/main/src/show-example.typ#L30) it becomes a block. If I understand the intent behind it correctly, I think this could go [here](https://github.com/Mc-Zen/tidy/blob/main/src/show-example.typ#L85-L88) instead.

**Comment by Mc-Zen** [comment]
Oh yes, this is pity. I didn't think about raw elements occuring in the rendered output. Your suggested fix looks good. For now, until a new version is released, you could work around that by specifying
```typ

#let module = tidy.parse-module(
  module,
  preamble: "set raw(block: false);"
)
```

Thanks for reporting!

**Comment by SillyFreak** [comment]
thanks, will try that!

**Comment by SillyFreak** [comment]
I just noticed that `lang` has basically the same issue: https://github.com/Mc-Zen/tidy/blob/main/src/show-example.typ#L38

**Comment by Mc-Zen** [comment]
Ah yes, I will fix this along the way

**Comment by Mc-Zen** [comment]
Both issues should be fixed now. These two examples 
```typ
#show-example(`a #raw("foo") b`, mode: "markup")
#show-example(`#raw("#import")`, mode: "markup")
```

produce

![image](https://github.com/Mc-Zen/tidy/assets/52877387/dfcda226-71ee-430a-9c51-ba657aea96a8)
