### ISSUE TITLE
How to document variadic arguments

### ISSUE THREAD

**Issue by johannes-wolf** [Mc-Zen/tidy#3]
Thank you for this project!

In CeTZ we use a lot of var-args `my-fun(..options)`, but I could find no way to 
get typst-doc to match the argument to my docstring line:

```
//// my-fun
/// - ..options (any): Text
```

does not work. Is this currently possible?

**Comment by Mc-Zen** [comment]
Hi @johannes-wolf ,
Yes, I also came across this with quill and it is already fixed but not pushed yet!

> `/// - ..options (any): Text`

is (will be) the correct way. 

I am currently working on the interface for allowing ouput style customization and this delayed the update.

**Comment by Mc-Zen** [comment]
By the way, I've already seen the current documentation of CeTZ (amazing work you have done there) some weeks ago and it features a lot of visual examples. Can I invite you to a discussion about (hopefully) supporting that in function descriptions? 

#4

**Comment by johannes-wolf** [comment]
> By the way, I've already seen the current documentation of CeTZ (amazing work you have done there) some weeks ago and it features a lot of visual examples. Can I invite you to a discussion about (hopefully) supporting that in function descriptions?
> 
> #4

Yes :). I was also thinking about support for examples. My idea was to support custom tags/blocks that one can register callbacks for. When rendering these tags/blocks, the callback is called to return content.

**Comment by Mc-Zen** [comment]
Oh sorry, the #4 was intended to be the link for the disussion and I explained the current status there but anyway :D

This is a great idea!

**Comment by Mc-Zen** [comment]
Hi @johannes-wolf,
Could the cases that you have in mind be equally elegantly solved by passing a set of objects that will be added to the scope? What I mean:

```
// mymodule.typ

/// Function
/// - my-arg (int): Text
/// #example1
#let my-function(my-arg) = {}
```

```
// documentation.typ

#let example1 = [
   // this may call anything, even #image() and #import()
}
#parse-module(read("mymodule.typ"), scope: (example1: example1))
```

Or would the custom blocks and tags suggested by you add extra benefit or elegance? Because we could also have it both in that case.

**Comment by Mc-Zen** [comment]
alright, thanks for your feedback :)
