### ISSUE TITLE
`omit-empty-param-descriptions` is ignored

### ISSUE THREAD

**Issue by jneug** [Mc-Zen/tidy#6]
The setting seems to be ignored, because the description is compared to `[]` (empty content), but the default is `""` (empty string). See [styles/default.typ:114](https://github.com/Mc-Zen/tidy/blob/2b59d88724c64092c78ce33b178f91f6f9e35223/src/styles/default.typ#L114C41-L114C70) for example. 

I think something like `if description in ("", []) ...` would work better.

**Comment by Mc-Zen** [comment]
Oh right. I made some changes there shortly before the release and missed that. The default should be `[]`, not `""`. 

The issue only is with undocumented parameters. I fixed it on main and it will be in the next release :)


Thank you!
