### ISSUE TITLE
Move mandatory vertical space after function into style

### ISSUE THREAD

**Issue by jneug** [Mc-Zen/tidy#7]
[Line 122](https://github.com/Mc-Zen/tidy/blob/5e44a725485d09ace5de8d132b4fe09e227695bc/src/tidy.typ#L122) adds a vertical space of `3em` after each function. Maybe this could be moved to the style, to allow custom spacing for different templates.

**Comment by Mc-Zen** [comment]
This sounds reasonable. I will change that

**Comment by Mc-Zen** [comment]
This sounds reasonable. I will change that
